# Generated by Django 5.1.6 on 2025-02-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='bio',
            new_name='profile_details',
        ),
    ]
