# Generated by Django 5.1.6 on 2025-02-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_position_alter_candidate_event_and_more'),
        ('events', '0003_candidate_position_alter_candidate_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
