# Generated by Django 5.1.6 on 2025-02-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('events', '0002_alter_event_name_candidate_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='bio',
            new_name='profile_details',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='events.event'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
