# Generated by Django 5.1.6 on 2025-02-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_event_alter_candidate_user'),
        ('events', '0003_candidate_position_alter_candidate_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('chair_person', 'Chair Person'), ('vice_chair_person', 'Vice Chair Person'), ('event_head', 'Event Head'), ('creativity_head', 'Creative Head'), ('hr_head', 'HR Head'), ('pr_head', 'PR Head'), ('ond_head', 'OND Head'), ('finance_head', 'Finance Head')], default='other', help_text='Select the position the candidate is contesting for.', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='events.event'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
